from enum import Enum, auto

CONTEXT_KEY_COGNITO_SERVICE = "aws_cognito_service"
CONTEXT_KEY_TOKEN_SERVICE = "aws_jwt_service"

CONFIG_KEY_POOL_ID = "AWS_COGNITO_USER_POOL_ID"
CONFIG_KEY_REGION = "AWS_DEFAULT_REGION"
CONFIG_KEY_DOMAIN = "AWS_COGNITO_DOMAIN"
CONFIG_KEY_POOL_CLIENT_ID = "AWS_COGNITO_USER_POOL_CLIENT_ID"
CONFIG_KEY_POOL_CLIENT_SECRET = "AWS_COGNITO_USER_POOL_CLIENT_SECRET"
CONFIG_KEY_REDIRECT_URL = "AWS_COGNITO_REDIRECT_URL"

HTTP_HEADER = "Authorization"
